server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: jms-template, jms-listener

  jms:
    template:
      default-destination: tacocloud.order.queue
      receive-timeout: 2
    cache:
      enabled: false
  artemis:
    broker-url: localhost:61616
    user: ryu 
    password: 1234 
    embedded:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: kafka

  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos