# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Artemis properties.
spring:
  profiles:
    active: jms-template
---
spring:
  config:
    activate:
      on-profile: jms-template

  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    broker-url: localhost:61616
    user: ryu  
    password: 1234 
    embedded:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: kafka 
      
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer    