spring:
  profiles:
    active: jms-template 
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: jms-template 
  jms:
    template:
      default-destination: tacocloud.order.queue
    cache:
      enabled: false
  artemis:
    broker-url: localhost:61616
    user: ryu  
    password: 1234 
    embedded:
      enabled: false
    